### ISSUE TITLE
Invalid Assumptions about how to pull metadata from WLNUpdates.

### ISSUE THREAD

**Issue by fake-name** [gmathi/NovelLibrary#106]
Hi there!

It seems like your application uses one of my projects (WLNUpdates.com) as a backend! Awesome!

That said, is there a reason you don't use [the API](https://www.wlnupdates.com/api-docs)? I have a pretty comprehensive API that basically exposes all the queries that I use to render the normal HTML views as convenient JSON objects. 

Anyways, what got me looking at this project is that you seem to be making a number of assumptions about how chapters on wlnupdates are structured that aren't valid, and it's annoying at least one person enough that they [posted about it on the forums](https://www.wlnupdates.com/forum/release-errors/1947).

Anyways, I haven't looked too closely, but you seem to be missing handling for a few specific cases.

Specifically:
 - Chapter count **does not** correspond to a new chapter being available. 
 - Excluded chapters are not excluded.

The thing that makes WLNUpdates novel (at least I hope), is that I try very hard to figure out correct chapter numbers from what is basically nearly unstructured text. I then use that data for managing chapter reading progress.

As a result of this, there are facilities for handling invalid chapters (either due to a mistaken parse, or more commonly the hosting site posting things incorrectly. It happens more then you'd think!). There is as such the facility for specifying that specific releases are *not included* when evaluating the most recent chapter. 

From what I can tell, you don't have a provision for tracking this.

Additionally, I currently consume data from multiple sources. Right now, I'm in the process of adding tracking for content on ScribbleHub. As part of this, I automatically merge series on scribblehub and royalroad depending on a number of heuristics. This means that the number of chapters for a series is increasing (to 2x the actual content chapters) without any new content actually being available. 

The chapter extraction system in place handles this quite gracefully, as it knows that "chapter 25" on one site is equivalent (in a reading progress sense) to "chapter 25" on the other. However, if you are using a mechanism that just counts the available releases ([which seems to be what is going on](https://github.com/gmathi/NovelLibrary/blob/bfc7abb38b3905b673e128574207d4e30e1d2c57/app/src/main/java/io/github/gmathi/novellibrary/network/NovelApi_ChapterCount.kt#L62-L70)), you're going to get wildly incorrect results.

Ideally, it'd be awesome if you integrated support for the WLNUpdates reading list system (it's exposed through the API, and provides handy things like shortlinks to the latest unread chapter, etc...), but at minimum, you should really consider using the API to get the latest available release. The [`get-series-id`](https://github.com/fake-name/wlnupdates/blob/master/app/apiview.py#L112) API query provides both [structured](https://github.com/fake-name/wlnupdates/blob/cdee4a26d3a71d4bdd6bfc453977395850a6c476/app/api_handlers_anon.py#L365) and [human readable](https://github.com/fake-name/wlnupdates/blob/cdee4a26d3a71d4bdd6bfc453977395850a6c476/app/api_handlers_anon.py#L367) versions of the relevant metadata, as well as probably everything you'd need to completely replace your entire [`getWlnNovelDetails`](https://github.com/gmathi/NovelLibrary/blob/bfc7abb38b3905b673e128574207d4e30e1d2c57/app/src/main/java/io/github/gmathi/novellibrary/network/NovelApi_Novel.kt#L81-L151) invocation with something less brittle. It also doesn't require any auth.

**Comment by gmathi** [comment]
Awesome! Thanks for this information. I will read up the API and make changes my side in about ~2-3 weeks.

I will definitely reach out to if I have any questions!

**Comment by fake-name** [comment]
Woot!

**Comment by gmathi** [comment]
@fake-name QQ: What is the input json for `get_series_id` and `get-series-data`?

**Comment by fake-name** [comment]
[Docs should be updated](https://www.wlnupdates.com/api-docs), and I went through and added example post/responses for the rest of the stubs. 

Both calls (`get_series_id`/`get-series-data`) call the same actual API functions.  I can't remember why the heck I started renaming stuff `xxx-data` at some point, but I have a bunch of duplicated calls with just different names. They're literally identical internally, they all map to the same function in the internal dispatch table.

**Comment by gmathi** [comment]
@fake-name  Found a minor bug in API. 

Basically, when we make the call to get series information the JSON that is returned has this format as far as I noticed. 
`
"authors": [
            {
                "author": "Takeru Uchida",
                "id": 248
            }
]
`
As you have seen above the parent is **plural** _authors_ and the child element is **singular** _author_. I noticed the same pattern with **tags**, **genres**, e.t.c 
The only one that doesn't follow this pattern is **illustrators**. Just wanted to bring this to your notice.
Keep me notified if you ever make a fix for this, as I will update it on my side too.

**Comment by fake-name** [comment]
Huh, that seems to be a plain old-fashioned [typo](https://github.com/fake-name/wlnupdates/blob/fe5d0d17768ed786f101ea516db96cbf46f28935/app/api_handlers_anon.py#L318-L323). Good catch.

**Comment by gmathi** [comment]
@fake-name Sorry to bug you so soon, found another thing. When I am pulling the data for **Isekai cheat magician** novel, the releases data on the website is not consistent with the releases data the API is sending. 

For Example: 

The api returns this: 

> {
                "chapter": null,
                "fragment": null,
                "postfix": "Prologue 2",
                "published": "Thu, 28 Jun 2018 09:03:34 GMT",
                "series": {
                    "id": 231,
                    "name": "Isekai Cheat Magician"
                },
                "srcurl": "http://shmtranslations.com/2017/08/28/chapter-2-prologue-2/",
                "tlgroup": {
                    "id": 1316,
                    "name": "SHMTrans"
                },
                "volume": null
            },

As you can see, there is no chapter name/number associated with it.

Where as on the website, there is a chapter number associated with it: 

> | Isekai Cheat Magician | 2 | Prologue 2 | SHMTrans

I would like to know if I am missing something or is there another API which can return detailed releases data.



`

**Comment by fake-name** [comment]
Hey, I'd rather know about issues then have them just be there breaking people's viewing/api experience.

**Comment by fake-name** [comment]
Should be fixed now.

**Comment by gmathi** [comment]
Hey thanks for the help. I am done moving my code to use the API instead of web scraping. The only place I am using scarping is to parse the document returned from hyperlinks. 

One thing I would like to request as an enhancement to the API is to include rating as part of the 
`search-advanced` mode in the `include-results`.

**Comment by fake-name** [comment]
> One thing I would like to request as an enhancement to the API is to include rating as part of the
search-advanced mode in the include-results.

Ok, added. This isn't a expensive addition (it doesn't require an additional queries), so I just added it by default. I also added some additional fields:


Request:

```
{
	'mode': 'search-advanced', 
	'title-search-text': 'Isekai'
}
```

Response:

```
{
	"data": [
		{
			"extra_metadata": {
				"is_yaoi": false,
				"is_yuri": false
			},
			"id": 73478,
			"latest_published": 1541891770.0,
			"rating": null,
			"rating_count": null,
			"release_count": 6,
			"title": "Absurd Isekai Mage",
			"tl_type": "oel"
		}, {
			"extra_metadata": {
				"is_yaoi": false,
				"is_yuri": false
			},
			"id": 2183,
			"latest_published": 1576340951.0,
			"rating": null,
			"rating_count": null,
			"release_count": 14,
			"title": "Aim for the Deepest Part of the Different World Labyrinth",
			"tl_type": "translated"
		}, {
			"extra_metadata": {
				"is_yaoi": false,
				"is_yuri": true
			},
			"id": 60637,
			"latest_published": 1550187724.0,
			"rating": 7.4,
			"rating_count": 5,
			"release_count": 66,
			"title": "Aiming For Harem Queen in Different World \\u2013Story of Self-Proclaimed Ordinary High School Girl Struggling in Different World\\u2013",
			"tl_type": "translated"
		}

		<....snip....>
	],
	"error": false,
	"message": null
}
```

Principally, I added the series type by default (which I should really add to the web views too), and the `extra_metadata` column, which right now is used for caching additional info about a series that I might want in a table view. So far, it's just for the Yaoi/Yuri icon indicators in the main view. It's a `JSONB` column in the database.

Note: This column is basically a caching facility. You probably shouldn't assume things will *always* be present (well, you should handle them being missing). The facilities that update the cached value don't happen at the same time as series creation, so it's possible to have a newly created series without any `extra_metadata`entries, or just some of the values.

Additionally, I may add more things in the future here, but since it's a dict that shouldn't affect any usage of the present fields. I'll also try very hard to not change the types of the entries that I do add. 


> Also, the covers returned as part of the the above API are not formatted properly.

Lol, I fail at protocol relative URLs. Anyways, they all return fully qualified URLs, since anything touching the API isn't likely to need to know how to hit my testing env (which doesn't have HTTPS termination, because it's done by a nginx reverse proxy on the production site).

**Comment by gmathi** [comment]
Np! Thanks for the update. Will add these changes in to app as part of next release.

**Comment by fake-name** [comment]
Awesome!
