### ISSUE TITLE
Chapters loading wrong

### ISSUE THREAD

**Issue by jopejoe1** [gmathi/NovelLibrary#116]
Some of the Re:Monster Chapters Translate by Re: Translation have a to big width example c4 and c7 
And all the translations from re: monster wikia are not readable in night mode.

Cheers Jopejoe1
![Screenshot_20200807-050810_Novel Library](https://user-images.githubusercontent.com/34899572/89562163-acc75180-d86d-11ea-8067-53a50e591ce1.jpg)
![Screenshot_20200807-052040_Novel Library](https://user-images.githubusercontent.com/34899572/89562229-c23c7b80-d86d-11ea-83e7-5dff46db37c2.jpg)

**Comment by gmathi** [comment]
I will fix this as part of next release! Thanks for reporting. (I also saw your message on discord)
