### ISSUE TITLE
I can't refresh novel-updates and LNMTL

### ISSUE THREAD

**Issue by mcOz1** [gmathi/NovelLibrary#137]
I have huawei y6p so i can't download this app from google play. I installed from web. When I lunch novel library and try search some novels, on the tab "novel updates" i see "no novels found" and on the tab "LNMTL" i see "Commection error". How i can fix this?

**Comment by DonielMoins** [comment]
Can you verify a couple of things? Such as:

0) Internet connectivity,

1) Try to open Novel updates on your phone to make sure it's not blocked,

2) Backup your data, Reinstall the app, and test novelupdates search before
restoring from backup.

3) Take a video! it can help a lot.

4) Try a VPN?

5) Device specs?

what phone, Android version, app version, country(some areas block certain
websites) any info that you think can help us

What Novel are you looking for? Look for it on the website, (not from the
app), do you find it?

**Comment by DonielMoins** [comment]
most importantly, where from the web did you download the app? from our
discord? from this GitHub? Cause those are the only 2 reliable sources of
the APK.

**Comment by mcOz1** [comment]
I didn't know, that i can download apk from your's discord. after download the lastest version, app is working.

**Comment by DonielMoins** [comment]
Perfect, have a great day.
