### ISSUE TITLE
Ability to copy chapter URL so it can be pasted elsewhere (ex: browser)

### ISSUE THREAD

**Issue by gmathi** [gmathi/NovelLibrary#159]
Ability to copy the URL of the current chapter while in reader mode. If that is not possible, then have the ability to copy the chapter URL from the Chapters screen.

**Comment by RohitKing2001** [comment]
Well it's working fine for🙄

**Comment by gmathi** [comment]
> Well it's working fine for me🙄

This is already there? Where exactly?

**Comment by Bm12347** [comment]
> > Well it's working fine for me🙄
> 
> This is already there? Where exactly? 

Yes it really exists![Screenshot_20210217-195109_Novel Library.jpg](https://user-images.githubusercontent.com/66433732/108245956-902f9e80-7159-11eb-8bc9-087031bce52d.jpg)

**Comment by codefionn** [comment]
I have encoutered an weird issue where my Android 11 Phone didn't want to open the page in a new browser tab

**Comment by gmathi** [comment]
"Open in Browser" : This is not working on some new phones. Need to test this out.

**Comment by gmathi** [comment]
Found out the root cause of this issue. Will be fixed in next release (after 0.20.beta one)

**Comment by Efreak** [comment]
This doesn't copy the URL for the open page, unfortunately, it copies the URL for the chapter that was initially opened. This means it you have to click a link to open the actual chapter, you can't use this button to open the chapter in an app that converts to pdf or does other processing on the URL.

For example, every single novel updates chapter URL is in the form of "https://www.novelupdates.com/extnu/######", meaning that if I try to open a chapter while NU is down, I can't get there at all. This isn't a frequent occurrence, and usually lasts no more than a few seconds, but it's frustrating.
