### ISSUE TITLE
Empty Alert When Queueing Downloads

### ISSUE THREAD

**Issue by mindreave** [gmathi/NovelLibrary#160]
Running 0.17.beta_96
When attempting to queue downloads for Overgeared found on NovelUpdates and hosted on WuxiaWorld, an empty Alert is raised.
Happens when using Download All and selected chapters, including just the first chapter.
Chapters can be read normally.

![image](https://user-images.githubusercontent.com/5333537/107130893-dac23880-6886-11eb-8637-87b2b22b0f44.png)

**Comment by gmathi** [comment]
Next update 0.18.5 will have this
