### ISSUE TITLE
World's Fastest Level Up rewriting to latest saved downloaded file

### ISSUE THREAD

**Issue by Lytzchu** [gmathi/NovelLibrary#169]
![Screenshot_2021-02-10-23-39-45-542_io github gmathi novellibrary](https://user-images.githubusercontent.com/37210476/107587309-71527900-6c3c-11eb-9232-026cdec10475.jpg)
Novel rewriting to latest downloaded but the online browser story is ok

**Comment by gmathi** [comment]
I would imagine that all the pages being downloaded have the same title, there for overwriting the already downloaded files. 
I will look into this.

**Comment by gmathi** [comment]
Fixed this for the next update. You would need to re-download the chapters tho.
