### ISSUE TITLE
Swipe functionality for common actions

### ISSUE THREAD

**Issue by mindreave** [gmathi/NovelLibrary#174]
As a possible enhancement, the implementation of Swipe functionality for common tasks.

For example, Tachiyomi/Neko fork uses Swipe to bookmark chapters or to toggle chapters read/unread quickly.
https://github.com/CarlosEsco/Neko (Mangadex is currently down though, so hard to demonstrate without an existing install)

Possible functions:
Bookmark Chapter
Mark Chapter Read or Unread
Quick Add to library

**Comment by gmathi** [comment]
Would you able to create an issue for each of the above requests, so we can track them as they are completed?

**Comment by mindreave** [comment]
@gmathi Added. Left quick add to library for now, as it doesn't require a menu interaction and seems like a trivial convenience.
