### ISSUE TITLE
Add 'Edit Novel Category' in the context menu of Search Novel results

### ISSUE THREAD

**Issue by metaeatscake** [gmathi/NovelLibrary#183]
Could we get the option to edit the novel category from the search results context menu? Sometimes I get lost on where I put a certain series

[Sample picture of the menu](https://cdn.discordapp.com/attachments/339611455013781506/833362596102406154/Screenshot_20210418-232352_Novel_Library.jpg)

**Comment by gmathi** [comment]
Fixed in 0.18 branch
