### ISSUE TITLE
Special characters that are problematic for Read Aloud

### ISSUE THREAD

**Issue by alsderda** [gmathi/NovelLibrary#190]
some characters are anoying when using Read Aloud when they are used in in larger amounts by the translators and make the novel harder to understand, so it would be nice if the Read Aloud function could ignore them
characters that i noticed
"=",">","<","|"

**Comment by gmathi** [comment]
I think @Yanrishatum is already planning to work towards this. Tagging @Yanrishatum so he is aware of this issue reported.

**Comment by alsderda** [comment]
Just noticed "+" had the same problem

**Comment by Yanrishatum** [comment]
If you discover any other problematic characters, please report them in #208
