### ISSUE TITLE
Search results sometimes load wrong cover image

### ISSUE THREAD

**Issue by japzone1** [gmathi/NovelLibrary#216]
Example: Search "golden cross", observe the image shown in the search results for the novel, look at the actual cover image shown on Novel Details and Novel Updates.

![Screenshot_20210831-095753659 (1)](https://user-images.githubusercontent.com/6744865/131516209-6e1160e2-d717-4ec3-97e0-469f6c5223d3.jpg)
![Screenshot_20210831-100047164 (1)](https://user-images.githubusercontent.com/6744865/131516269-2b624ffb-12b7-4d66-b9ea-05fcda9da2be.jpg)

**Comment by codefionn** [comment]
Close this issue. This is not bug (of NovelLibrary).

Checked it and this is a bug by courtesy of novelupdates.com and not the app.

**Comment by japzone1** [comment]
> Close this issue. This is not bug (of NovelLibrary).
> 
> Checked it and this is a bug by courtesy of novelupdates.com and not the app.

Wow, really? That's dumb.
