### ISSUE TITLE
Continuous Volume Scrolling

### ISSUE THREAD

**Issue by japzone1** [gmathi/NovelLibrary#53]
**Expected Behavior:**
Holding down one of the volume buttons causes the page to scroll until the button is released.

**Current Behavior:**
Holding down one of the volume buttons causes the page to scroll once, and then hang. Releasing the button causes it to scroll once more and then it stops.

**Comment by gmathi** [comment]
I need to research on this. But I will leave this if any other dev can work on it.
@aouerfelli @Arthur-Tesse

**Comment by aouerfelli** [comment]
I think there should be an option in the future to switch between paginated scrolling and step (line) scrolling. For now, I'll switch it to do line scrolling and you can decide if you want to keep it in the code review.
