### ISSUE TITLE
NovelUpdates' Cloudflare protection

### ISSUE THREAD

**Issue by Arthur-Tesse** [gmathi/NovelLibrary#60]
Now, NovelUpdates is protected by Cloudflare's distributed network 😭.

It doesn't matter !

The real IP is 45.79.90.67 and using the HTTP header `Host: www.novelupdates.com`, it can be accessed again !

**Comment by gmathi** [comment]
Great! I will review it!!

**Comment by aouerfelli** [comment]
Can confirm that it works. Awesome stuff!

**Comment by gmathi** [comment]
Ok. Let me get a hold of my laptop and make a fix then!

**Comment by gmathi** [comment]
Or if you can do that and make a pull, that would be awesome too!

**Comment by Arthur-Tesse** [comment]
If only I had my computer right now...

**Comment by gmathi** [comment]
Ok started the work on it.

**Comment by gmathi** [comment]
Tested bunch of stuff and seems like only the reader mode is failing to load (which is the core part of the app). 

Url: https://www.novelupdates.com/extnu/189973/
Converted url: http://45.79.90.67/extnu/189973/
Added header to that: "host" ,"www.novelupdates.com"

Now this converted url, with that host header works in the postman. But, somehow it fails to do the same in app. Not sure if there is problem with redirecting. I tried using the libraries "Jsoup" & "okHttp"

**Comment by Arthur-Tesse** [comment]
For this, you should look for a `Location: whatever.ext/mylink/novel` and it will provide the link to the redirection.

You can look at it using the network tab of the debug zone of your browser (Firefox, Chrome, IE?)

**Comment by aouerfelli** [comment]
Looks like they aren't using the Cloudflare DDOS protection anymore. It can probably be removed at this point.

**Comment by gmathi** [comment]
Sure. Let me push the current release, then we can remove/comment it out.
