### ISSUE TITLE
Custom reader settings

### ISSUE THREAD

**Issue by kratos301** [gmathi/NovelLibrary#61]
little quality of life suggestion: custom reader settings for specific novels. 

While i use reader mode for almost all of them (i mean.. it's really well done and it's the main point of the app in the first place) some novels site are oddly designed and it's just better to read without reader mode, and some force you to have javascript on and reader mode off to watch their ads to gain access to the novel.

It's nothing essential of course, you spend a few seconds each time to change the settings, reload the chapter and hope that cloudflare does not start bitchin all of a sudden, but it would be nice.

**Comment by gmathi** [comment]
Makes sense. I will try to work on this after I figure out a way to tag these reader settings to novels instead of storing them in the app data.
