### ISSUE TITLE
Issue with syzctranslations.github.io

### ISSUE THREAD

**Issue by transitracer** [gmathi/NovelLibrary#72]
With any combination of settings other than Reader Mode: Disabled and Javascript: Enabled, I get this

![screenshot_20180708-160428](https://user-images.githubusercontent.com/36526063/42423460-a8160c64-82c8-11e8-947f-d48abe3f9896.png)

With those settings, I get this (unreadable)

![screenshot_20180708-155938](https://user-images.githubusercontent.com/36526063/42423468-b6e92c12-82c8-11e8-87af-edfd42ad9226.png)

When loaded in the web browser I get this (actually readable)

![screenshot_20180708-155956](https://user-images.githubusercontent.com/36526063/42423474-cd220e4a-82c8-11e8-9dcc-d15af0b9b4e8.png)

I'm using 0.9.3.beta_55, the novel is Virtual World: Peerless White Emperor

**Comment by beta-phenylethylamine** [comment]
On a Nexus 5x running 7.1.2 PureNexus, but I doubt that's the issue

If I had to guess, the issue of the background being black may just be that the site doesn't set a background color and the reader defaults to black instead of white for some reason, no clue with Reader Mode

**Comment by gmathi** [comment]
That's a good find. I guess that website was not supported, as I have a
generic script to support 99% of the websites with reader mode. I will make
sure this is supported in the next update (0.9.5).

Also 0.9.4 is out. No more 0 chapters notifications!

-GGear
