### ISSUE TITLE
Submit to FDroid

### ISSUE THREAD

**Issue by transitracer** [gmathi/NovelLibrary#75]
I'd love to see this app end up on fdroid, as an alternative to downloading it off the play store.

**Comment by Poussinou** [comment]
This app could be very interesting for the F-Droid repo, but there are proprietary libraries like firebase and google libraries. We couldn't build this.

@gmathi I supposed it's not possible to get ride of them?

**Comment by gmathi** [comment]
@Poussinou You could build it without the google & firebase libraries. Make sure to comment/remove the code in your side of the fork when you build it. That way, you don't use any proprietary libraries.

**Comment by Poussinou** [comment]
I'm not willing to maintain a full-FLOSS fork myself, we would better need a gradle build flavor that comes without non-free stuff

**Comment by gmathi** [comment]
Sorry @Poussinou I am not quite free right now, to do that. Hardly making time to work on the app itself. I wouldn't mind if some one did that though.

**Comment by transitracer** [comment]
What purpose does firebase serve in NovelLibrary? I might be interested in working on it if it's reasonably trivial (at least on the "writing new code" end, I can put in some grunt work).
